### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by pkbhadkoliya** [leantony/laravel-grid#15]
Hi,

Laravel 5.6 uses Bootstrap 4, any plans to upgrade to Bootstrap 4?

**Comment by leantony** [comment]
Yes. The next major version shall support bootstrap 4.0

**Comment by leantony** [comment]
You can preview the changes by adding `"leantony/laravel-grid": "2.0.x-dev",` to your composer.json file. Updating to bootstrap 4 is not a mundane process, but there are plugins that might not work, e.g the daterange selector, as there is no bootstrap 4 support for it.

**Comment by leantony** [comment]
#17 
I've added support for laravel 5.5. This is released by the tag `1.0.*`. It's the current stable version that's working well. Bootstrap 3 by default.
For bootstrap 4 support, you'll have to get the release tag `2.0.*`. It's currently still in development, and should be ready in 2 weeks time.

**Comment by leantony** [comment]
https://github.com/leantony/laravel-grid/tree/2.0
