### ISSUE TITLE
Configure grid 

### ISSUE THREAD

**Issue by AndreaRunner** [leantony/laravel-grid#16]
Hi Leantony,
i dont' know how to check/install the requirements for your grid.
However i have create the grid but i dont'know how  to configure button create, refresh, export, view or delete.

For example for the button view i have written this code: 
**web.php:**
Route::resource('sals', 'SalsController');

**SalsController.php:**

public function show($id, Request $request) {

        $sal = Sal::query()->findOrFail($id);
        $data = [
            'model' => class_basename(Sal::class),
            'route' => route('sals.update', ['sal' => $sal->id]),
            'data' => $sal,
            'dataVars' => [
                'pjax-target' => '#' . $request->get('ref')
            ],
            'method' => 'patch',
            'action' => 'update'
        ];
    // modal
        return view('sals_modal', $data)->render();
    }

**sals_modal.blade.php:** 
@if(isset($method))
    {!! BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [2, 10]])->action($route)->class('form-horizontal')->id('modal_form')->data($dataVars ?? [])->$method() !!}
@else
    {!! BootForm::openHorizontal(['sm' => [4, 8], 'lg' => [2, 10]])->action($route)->class('form-horizontal')->id('modal_form')->data($dataVars ?? [])->post() !!}
@endif
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">{{ ucwords($action . ' '. class_basename($model)) }}</h4>
</div>
<div class="modal-body">
    <div id="modal-notification"></div>
    @if(isset($data))
        {!! BootForm::bind($data) !!}
    @endif    
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;{{ 'Close' }}
    </button>
    <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i>&nbsp;{{ 'Save' }}</button>
</div>
{!! BootForm::close() !!}

but view button doesn't work
Help me please.
Thanks

**Comment by leantony** [comment]
For installing requirements, please read through https://github.com/leantony/laravel-grid/wiki/Installation#requirements, if you haven't.

The modal uses [bootform](https://github.com/avengers/bootforms), so I'll suggest you go through their documentation too, just to get a feel of how it works. The bootforms package though, is not really a requirement - you can just as easily rewrite the provided form template to your needs, but of course ensuring that the added variables remain.

To customize the buttons, please go through this wiki - https://github.com/leantony/laravel-grid/wiki/Customize-buttons
