### ISSUE TITLE
Class 'Leantony\Grid\Filters\SortDataHandler' not found

### ISSUE THREAD

**Issue by pkbhadkoliya** [leantony/laravel-grid#18]
Latest 2.0 build is failing in vendor/leantony/laravel-grid/src/Listeners/HandleUserAction.php

Remove:
use Leantony\Grid\Filters\SearchDataHandler;
use Leantony\Grid\Filters\SortDataHandler;

As it is moved to Listeners folder.

**Comment by leantony** [comment]
It's still in development. I'm working on it at the moment

**Comment by leantony** [comment]
major issues fixed as of fad87e4. Please update and let me know any issues you encounter by raising them here on github.
