### ISSUE TITLE
Cloning project

### ISSUE THREAD

**Issue by AndreaRunner** [leantony/laravel-grid#27]
Hi,
is possible "git clone" the project to have a fully working application?
Andrea

**Comment by leantony** [comment]
No. This is a package, so you need a working laravel installation to install it. By running `composer install ...`. If you are stuck, you can ask a question here, or you can try cloning https://github.com/leantony/laravel-grid-app, which is the app that runs the demo on http://laravel-grid.herokuapp.com/

**Comment by AndreaRunner** [comment]
I have cloned https://github.com/leantony/laravel-grid-app ,
composer install,
npm install,
change .env to my requirments,
php artisan key:generate
php artisan migrate, 
add in boot of AppServiceProvider the string   Schema::defaultStringLength(191); 
but when i try to populate the user table with create button i have the error:
A server error occurred...
![image](https://user-images.githubusercontent.com/38216051/40118779-26bc7a1c-591b-11e8-909e-4285f5115e0c.png)
I dont' know how to install requirements (step by step)

**Comment by leantony** [comment]
Check the browser's http requests. It should show you what is causing the AJAX error

**Comment by leantony** [comment]
You need to know how to use browser development tools, for you to be able to easily and efficiently debug errors on the frontend. Please check [this page](https://www.lifewire.com/web-browser-developer-tools-3988965), in-order to familiarize yourself
