### ISSUE TITLE
Route [sals.create] not defined.

### ISSUE THREAD

**Issue by AndreaRunner** [leantony/laravel-grid#34]
I've tried to use this package in my app.
i've create the grid with an existing model
Below some configuration:

**AppServiceProvider.php:**
public function register()
    {
        $this->app->bind(SalsGridInterface::class, SalsGrid::class);      
    }

**web.php:**
Route::get('/', 'SalsController@index');

**SalsController.php:**
public function index(SalsGridInterface $salsGrid, Request $request) {
        return $salsGrid->create(['query' => Sal::query(), 'request' => $request])        
            ->renderOn('render_grid', [
                'generation_command' => 'php artisan make:grid --model="App\User"',
                'grid_code' => "https://gist.github.com/leantony/245d13514c962b92a60d057218e1cce1.js",
            ]);
    }

but i've an error when i open the home page:
Route [sals.create] not defined.

what is wrong ?

**Comment by leantony** [comment]
Add the `sals.create` route on the web.php file
```php
Route::get('/create', 'SalsController@create');
Route::post('/create', 'SalsController@store');
```
And you can rectify your index method on the controller to sth like this...
```php
public function index(SalsGridInterface $salsGrid, Request $request) {
    return $salsGrid->create(['query' => Sal::query(), 'request' => $request])
                              ->renderOn('render_grid');
}
```

**Comment by AndreaRunner** [comment]
web.php
//Leantony package
Route::get('/', 'SalsController@index');
Route::get('/create', 'SalsController@create');
Route::post('/create', 'SalsController@store');

SalsController.php
public function index(SalsGridInterface $salsGrid, Request $request) {
    return $salsGrid->create(['query' => Sal::query(), 'request' => $request])
                              ->renderOn('render_grid');
}

error is the same:
InvalidArgumentException
Route [sals.create] not defined.

**Comment by leantony** [comment]
Try adding the routes like this;
```php
Route::get('/create', 'SalsController@create', ['as' => 'sals.create']);
// the above is same as
Route::get('/create', 'SalsController@create')->->name('sals.create');
Route::post('/create', 'SalsController@store', ['as' => 'sals.store']);
```
You will need to familiarize yourself on routing in laravel. Please read this;
+ https://laravel.com/docs/5.6/routing#named-routes
+ https://laravel.com/docs/5.6/controllers#resource-controllers
