### ISSUE TITLE
custom route params

### ISSUE THREAD

**Issue by ayimdomnic** [leantony/laravel-grid#35]
@leantony good work on the package, I love it!

However, I working with it on a project and I can't seem to find a way to add my own route parameters a side from id, 

Example my url should be 
`https://app.example.com/admin/users/d4d42ea0-ee77-11e6-b823-6d63c6504afc`
but the package automatically does

`https://app.example.com/admin/users/1??ref=user-grid`
any thoughts around this

**Comment by leantony** [comment]
Try doing this...
```php
public function configureButtons()
    {
        // edit the view button
        $this->editRowButton('view', [
            'url' => function ($gridName, $item) {
                // update your url here
                return $this->getViewUrl([$gridName => $item->code, 'ref' => $this->getId()]);
            },
        ]);
    }
```
+ E.g use `$user->code` instead of `id`. `$item` in this case represents your model instance. `$gridname` is simply a route param name that's simply the singular form of the grid's name.
+ `ref` is used by the modal form to get the PJAX container to automatically refresh when an action is done

Do the same for the delete button. I'll add a much simpler way to define this soon

**Comment by ayimdomnic** [comment]
@leantony Thanks, I hadn't seen how extendable this was.. 

I know this will suffice, I hope I clear my backlog soon and create prs

Salute

**Comment by leantony** [comment]
I've added a much more easier way to update the model route parameter to use. Try updating the package again via composer, and modify the `setRoutes` method like this - for example;
```php
/**
     * Set the links/routes. This are referenced using named routes, for the sake of simplicity
     *
     * @return void
     */
    public function setRoutes()
    {
        // searching, sorting and filtering
        $this->setIndexRouteName('users.index');

        // crud support
        $this->setCreateRouteName('users.create');
        $this->setViewRouteName('users.show');
        $this->setDeleteRouteName('users.destroy');

        // default route parameter
        $this->setDefaultRouteParameter('id');
    }
```
Where `id` is the attribute you need accessed on the model instance.
