### ISSUE TITLE
An error will be occured when call makeCustomButton method

### ISSUE THREAD

**Issue by bbbbbbbk** [leantony/laravel-grid#51]
Appreciate for this project, it helps a lot!
And I find that an error will be occured when I call `makeCustomButton` like this(the parameter seems should be 'rows' but not 'row'):
```php
$this->makeCustomButton([
    'name' => 'home',
    'url' => url('/'),
 ],'rows');
```
And after I set a `renderIf` attribute it works,like this:
```php
$this->makeCustomButton([
    'name' => 'home',
    'url' => url('/'),
    'renderIf' => function(){
        return true;
    }
],'rows');
```

**Comment by leantony** [comment]
Try;
```php
$this->makeCustomButton([
    'name' => 'home',
    'url' => url('/'),
    'renderIf' => function(){
        return true;
    }
], static::$TYPE_ROW);
```
Sorry, some of the docs are abit behind, but will update them

**Comment by bbbbbbbk** [comment]
And I find that I must set the `tableColumns` attribute if I want use filters, like: 
```php
protected $tableColumns = [
    'id',
    'title',
    'status'
];
```
isn't in docs

**Comment by leantony** [comment]
If you want to filter, use this approach, as documented [here](https://github.com/leantony/laravel-grid/blob/master/docs/general.md#filter)
Assuming you want to display the columns {id, name and email} on the grid and a filter for them..

```php
/**
     * Set the columns to be displayed.
     *
     * @return void
     * @throws \Exception if an error occurs during parsing of the data
     */
    public function setColumns()
    {
        $this->columns = [
            "id" => [
                "label" => "ID",
                "filter" => ["enabled" => true, "operator" => "="],
                "styles" => ["column" => "grid-w-10"]
            ],
            "name" => [
                "search" => ["enabled" => true],
                "filter" => ["enabled" => true, "operator" => "="]
            ],
            "email" => [
                "search" => ["enabled" => true],
                "filter" => ["enabled" => true, "operator" => "="]
            ],
        ];
    }
```
The filter attribute on each column is used to create a filter. Do not use `tableColumns` as that is used internally to verify the columns that the user provides that they exist in the DB

I will be updating the docs, fixing typos, etc to minimize the confusion.

**Comment by bbbbbbbk** [comment]
OK,thanks.Here's another problem,when I use filter the filter will skip value 0,but there are attributes like `status` contains 0, I've viewed the source code and noticed the problem was caused by here:
```php
    /**
     * Check if provided user input can be used
     *
     * @param string|null $userInput
     * @return bool
     */
    public function canUseProvidedUserInput($userInput)
    {
        // skip empty requests
        if ($userInput === null || empty(trim($userInput))) {
            return false;
        }
        return true;
    }
```
In RowFilterHandler.php line 83, the method `canUseProvidedUserInput` will return false when `$userInput` is 0 but not empty

**Comment by leantony** [comment]
Thanks. I will look into that
