### ISSUE TITLE
Feature request : Optional card container OR Templating

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#57]
In some cases, we do not want the grid to be in a card container. For example when we want to have multiple grids inside one custom card container.

It's not so simple because you integrated data inside the card-header/footer, so we cannot just optionnally display card elements. The title can be dropped. But the pagination has to stay somewhere.

Another way of dealing with this, it to manage templates (so we can have multiple templates, and choose one of another for each of our grid).

**Comment by leantony** [comment]
Noted. I'll see how to get around this

**Comment by leantony** [comment]
See #67
