### ISSUE TITLE
Feature request : Ajax refresh/filter/nav

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#59]
Would be great to have an AJAX functionnality to load grid changes (filter, sorting, navigate trough pages, ...) via ajax instead of reloading the page.

I thought it was for that pjax was required, but it seems not ?

**Comment by Nuranto** [comment]
Something like 
in grid class : 
`
protected $useAjax = true;

[...]
public function setRoutes()
    {
      [...]
        $this->setAjaxRouteName('something.ajax'); 
      [...]
    }
`


and in controller : 

`


public function index(SomethingGridInterface $somethingGrid, Request $request)
    {
        return $somethingGrid
                    ->create(['query' => Something::query(), 'request' => $request])
                    ->renderOn('something.index');
    }

public function ajax(SomethingGridInterface $somethingGrid, Request $request)
    {
        return $somethingGrid
                    ->create(['query' => Something::query(), 'request' => $request])
                    ->renderAjax();
    }
`

**Comment by Nuranto** [comment]
I dug a little, and I see there actually is already pjax support !
So forget this issue.
However, I can't make pjax work... The ajax call seems ok, but pjax hard refresh anyway the page :(

**Comment by leantony** [comment]
Yes, PJAX support is available. You'll need server side middleware, and the pjax js dependency. Read more on the requirements section [here](https://github.com/leantony/laravel-grid#requirements).

I have never quite documented the PJAX functionalities yet, but only just. You can check [here](https://github.com/leantony/laravel-grid/blob/master/docs/buttons.md#enabledisable-pjax-on-button-click). I'm still in the process of documenting the package, so some docs may be incomplete or unavailable. But I tried as much as I could to document the major parts before I did a release.

**Comment by Nuranto** [comment]
No, you did great! It was a stupid mistake of mine, I did put the grid inside of a form by mistake... So when  submitting grid inputs, it was submitting the form at the same time of pjax, which looked like... the issue above :)
Anyway, sorry to bothered you with this, it works just fine !
