### ISSUE TITLE
Filters stopped working if table names are same as XXXGrid class name

### ISSUE THREAD

**Issue by pkbhadkoliya** [leantony/laravel-grid#70]
Column filters are not working.

**Comment by leantony** [comment]
What do you mean by this?

**Comment by pkbhadkoliya** [comment]
The scenario in which it wasn't working are as follow:
1) Separate db table name and grid class prefix. For example, db table name is "regions" but grid class name "PlacesGrid".
2) singular / plural differences: for example db table name is "region" & grid class name is "RegionGrid" still it wont work because it needs plural table names.

Able to fix the issue with overriding getGridDatabaseTable of Grid class.

**Comment by leantony** [comment]
How about overriding the function at https://github.com/leantony/laravel-grid/blob/a5cecf45e5f9e85aa7384436d4270aa36e75fa58/src/Grid.php#L241
To something like this on your grid?
```php
public function getGridDatabaseTable()
    {
        return function () {
            return 'some_other_table_name';
        };
    }
```
