### ISSUE TITLE
How to customize export pages?

### ISSUE THREAD

**Issue by rahulvenneers** [leantony/laravel-grid#71]
How can I customize the pdf generated from the export option? Thanks in advance.

**Comment by leantony** [comment]
```php
php artisan vendor:publish --provider="Leantony\Grid\Providers\GridServiceProvider" --tag=views
```
Then edit the file `reports/report.blade.php` as you wish. Just do not remove the two loops

**Comment by rahulvenneers** [comment]
I have one model called Purchase and one model called Car. I want to show
car model columns in Purchase. How can i do that?
