### ISSUE TITLE
Remove a button from grid

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#74]
Would be nice to have : 
```
removeRowButton
removeToolbarButton
```
functions. Which could be usefull on some "complex" inheritance cases.

I know there is `clearButtons` and `clearAllButtons`, but we sometimes want to remove only one button.

**Comment by Nuranto** [comment]
(I'm talking about `RendersButtons` trait)

**Comment by leantony** [comment]
You can try this in the meantime;
https://github.com/leantony/laravel-grid/blob/master/docs/buttons.md#enforcing-access-to-a-button-based-on-the-data-item

```php
public function configureButtons()
    {
        $this->editToolbarButton('create', [
            // only render this button if the user logged in owns the record
            'renderIf' => function () {
               return false;
            }
        ]);
    }
```
In this case, the create button will only be displayed if the `renderIf` callback returns true.
