### ISSUE TITLE
Remove filters

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#75]
In some cases, we need grids with very few rows.
In that case, filtering is useless.
Of course, we could use header class to hide it, but it would be better to disable it directly in the grid class.

**Comment by leantony** [comment]
https://github.com/leantony/laravel-grid/blob/master/docs/general.md#filter
```php
"name" => [
    "filter" => [
        "enabled" => true, // true/false
        "operator" => "="
    ],
]
```

**Comment by Nuranto** [comment]
Yes, but I was thinking of a global parameter.
In my case, I'm using a grid that extend another, and I want to disable filter only on the first one.
Using your method, i would need to surcharge the whole setColumns method which is not so good.
However, I can deal with that with a class parameter of my own in my parent class, so it's ok :)

**Comment by Nuranto** [comment]
@leantony  Added to that, the filter row and button "Filter" are still there even if I disable filter on every columns.
