### ISSUE TITLE
Enhancement : Filter placeholders

### ISSUE THREAD

**Issue by Nuranto** [leantony/laravel-grid#77]
ATM, we cannot set the filter title/placeholder.

For example : A column "Car", the placeholder on the filter input will be : "filter by car_id", and it cannot be changed easily.

Enhancement (quick) : replace "filter by car_id" by "filter by Car"
Enhancement (better) : add a filter option "title"

**Comment by leantony** [comment]
I'll be adding this.

**Comment by leantony** [comment]
check #78
